### ISSUE TITLE
Setup connection to blockchain & create substrate client (should impl `Client`)

### ISSUE THREAD

**Issue by tbraun96** [webb-tools/gadget#12]
We need a `Client` implementation that actually connects to the substrate blockchain. As of now, we are using mock blockchains in the form of servers or in-memory databases. We will need a real `Client` that accepts an address and outputs a connection to the blockchain itself, including the relevant API calls for accessing the pallets.

**Comment by shekohex** [comment]
I believe this one is done in your #37 PR? Right @tbraun96 ? If that so, please close this task.
