### ISSUE TITLE
[TASK] Abstract away on_finality_notification and client

### ISSUE THREAD

**Issue by tbraun96** [webb-tools/gadget#146]
To ensure maximum flexibility with other systems, `on_finality_notification` should be `on_event` or a similar yet generalized name. For example, a user may want to listen to a stream of events from a web server or another blockchain.

Additionally, the OnlineClient (subxt) and in general, the `Client` trait, should be abstracted further to generalize for the aforementioned reasons. For example, the client may check a webserver for a status, submit results, etc.

Both these requirements can be expressed using a `SourceConnection` or a similarly-named trait.

At the protocol-level (i.e., at the current moment, what we call the "external repository" that holds the protocol source code), the `SourceConnection` trait should be defined. 

We will also want to add a pre-defined trait for tangle. For example:

```rust
pub struct TangleConnection { .. }
impl SourceConnection for TangleConnection { .. }
```

**Comment by drewstone** [comment]
Might consider a different naming convention than `Connection`.
