### ISSUE TITLE
[CHECKLIST] Gadget SDK and Shell Manager

### ISSUE THREAD

**Issue by shekohex** [webb-tools/gadget#152]
## Gadget SDK

This SDK is primarily to help to have standard modules (a la `std`)  for Gadgets, it will live here in this repo under the `sdk` directory. We will keep each module behind a feature flag, and a `full` feature that would enable all of them by default.

- [x] #153
- [x] #155
- [x] #161
- [x] #156
- [ ] #163
- [x] #162
- [x] #200
- [x] #160

---

## Shell Manager

- [x] #157
- [x] #158
- [x] #159

## Repo
- [x] #164

### Resources
- https://github.com/supernovahs/eigensdk-rs

**Comment by drewstone** [comment]
Another Gadget CLI related checklist, linking for good measure https://github.com/webb-tools/gadget/issues/147

**Comment by drewstone** [comment]
Get to a point where it's easy to build and integrate for public examples & distribution.
- Relayers for different protocols w/ Tangle (and Eigenlayer) contract templates (for job verification/slashing verification)
- Nodes / infra for different protocols like Chainlink, Hyperlane, etc.
- MPC integrations w/ basic API and onchain job verification/slashing verification

Developer experience should become an easy step-by-step process similar to EL’s that Donovan is running through for example
1. Clone repo or (gadget create)
2. Build your verifiers/slashers
3. Deploy to local w/ tests
4. Deploy to testnet
5. Deploy to mainnet

Then big next milestone is figuring out:
- Service level agreement verification/slashing primitives
- zkVM verification/slashing primitives (macros to automate this)

**Comment by drewstone** [comment]
Recall, we need to prioritize this checklist @tbraun96 @shekohex. If things need to be updated, please jumpstart these conversations.
