### ISSUE TITLE
[CHECKLIST] Gadget SDK - Testing And Benchmarking Modules

### ISSUE THREAD

**Issue by shekohex** [webb-tools/gadget#162]
# Testing framework
The testing framework should be agnostic over the Blueprint being executed. It needs to support any Blueprint developer out of the box. That means as a Blueprint developer, I should have tools to hook into to test my Blueprint that speeds up development and testing. Instead of having macros such as `generate_signing_and_keygen_tss_tests` we need a macro called `generate_blueprint_tests`. This macro should take as input the respective jobs and additional test functions provided by the Blueprint developer to execute the following flow:

- In a mock runtime, deploy the Blueprint.
- Register `N` operators for the Blueprint.
- Submit jobs for each job/task defined by the Blueprint
- Provide the results of the job submissions and verify `ok` and `succeed` of submission.
- Provide negative tests, malicious behavior, slashing conditions.

## Testing abstractions
All jobs submitted for an active service blueprint are done using the pallet functionality. This will also eventually be possible through EVM precompiles so we must also remember to make sure we have the same flows testable using EVM precompiles.

- The testing framework should leverage the Blueprint proc-macro system to generate functions for submitting tasks for each task defined in a blueprint.
- Using the proc-generated testing code, tests should be as easy as implementing stateful checks that jobs were correctly completed.
- Using the proc-generated testing code, tests should be able to thoroughly conduct negative tests to test what happens when jobs fail (think on this and discuss).

## Benchmarking
We would like to understand the computational requirements of each task/verification/slashing offchain as a means for recommending node specifications and other important information for node operators. Consider the set of useful questions and insights below to identify how we can build a robust addition here:
1. How can we understand the computational requirements of each job (storage, compute, bandwidth requirements).
2. How to translate computational requirement output into node specs (4,8,16,256 GB RAM, 100,200, 1k GB SSD, etc.)
3. Libraries to help here.

# Implementation Steps

Overall, the task checklist in causal order:

**Core** 

- [x] #207
- [ ] #208
- [ ] #209
- [ ] #210
- [ ] #211
- [x] #212

**Secondary Tasks**

- [ ] #213
- [ ] #214

**Comment by drewstone** [comment]
I imagine the testing framework spawns Shells as the top level object and not Gadgets first. If that doesn’t make sense, previously we defined 5 gadgets to run. I would rather us define 5 shells to run, and enforce that every test run through the registration process for the Blueprints to ensure we are always satisfying a Blueprint’s registration. Then it instances the Blueprint, creates jobs, provides easy functions from proc-gen code to execute and verify output.

**Comment by drewstone** [comment]
Possibly useful: https://github.com/paritytech/polkadot-sdk/tree/master/substrate/frame/benchmarking

**Comment by drewstone** [comment]
More thoughts and playing around with Claude 3.5
```rust
use criterion::{black_box, criterion_group, criterion_main, Criterion, BenchmarkId};
use your_crate::{Job, my_job};

fn benchmark_job<T: Job>(c: &mut Criterion, job: T, input: &str) {
    let mut group = c.benchmark_group(format!("Job: {}", T::metadata().name));
    group.bench_with_input(BenchmarkId::new("execution", input), input, |b, i| {
        b.iter(|| T::execute(black_box(i.to_string())))
    });
    group.finish();
}

fn job_benchmarks(c: &mut Criterion) {
    benchmark_job(c, my_job, "sample input");
    // Add more jobs here as needed
}

criterion_group!(benches, job_benchmarks);
criterion_main!(benches);
```

```rust
use criterion::{Criterion, Measurement};
use std::time::Instant;
use sysinfo::{System, SystemExt, ProcessExt, PidExt};

struct DetailedMeasurement {
    start_time: Instant,
    start_memory: u64,
    system: System,
}

impl Measurement for DetailedMeasurement {
    type Intermediate = (Instant, u64);
    type Value = (std::time::Duration, i64, u64);

    fn start(&self) -> Self::Intermediate {
        (Instant::now(), self.system.process(std::process::id().as_u32()).unwrap().memory())
    }

    fn end(&self, start: Self::Intermediate) -> Self::Value {
        let duration = start.0.elapsed();
        let end_memory = self.system.process(std::process::id().as_u32()).unwrap().memory();
        let memory_diff = end_memory as i64 - start.1 as i64;
        (duration, memory_diff, end_memory)
    }

    fn add(&self, v1: &Self::Value, v2: &Self::Value) -> Self::Value {
        (v1.0 + v2.0, v1.1 + v2.1, v1.2.max(v2.2))
    }

    fn zero(&self) -> Self::Value {
        (std::time::Duration::from_secs(0), 0, 0)
    }
}

fn benchmark_job_detailed<T: Job>(c: &mut Criterion<DetailedMeasurement>, job: T, input: &str) {
    let mut group = c.benchmark_group(format!("Job: {}", T::metadata().name));
    group.bench_with_input(BenchmarkId::new("execution", input), input, |b, i| {
        b.iter(|| T::execute(black_box(i.to_string())))
    });
    group.finish();
}

fn job_benchmarks(c: &mut Criterion<DetailedMeasurement>) {
    benchmark_job_detailed(c, my_job, "sample input");
    // Add more jobs here as needed
}

criterion_group! {
    name = benches;
    config = Criterion::default().with_measurement(DetailedMeasurement {
        start_time: Instant::now(),
        start_memory: 0,
        system: System::new_all(),
    });
    targets = job_benchmarks
}
criterion_main!(benches);
```
