### ISSUE TITLE
[TASK] Eigen Interoperability - eigen-utils

### ISSUE THREAD

**Issue by Tjemmmic** [webb-tools/gadget#191]
### eigen-utils
- [x] BLS Signing Logic
- [x] ECDSA Keys
- [x] Reads Keys

**Comment by drewstone** [comment]
This is great @Tjemmmic. I even recommend breaking this out even further. If fixing BLS stuff is 1 task and can be assigned X points, we should be breaking it into its own task so we can close that out and claim the success.

**Comment by Tjemmmic** [comment]
Moved to https://github.com/webb-tools/eigensdk-rs
