### ISSUE TITLE
[TASK] Eigen Interoperability - Trust Modeling

### ISSUE THREAD

**Issue by drewstone** [webb-tools/gadget#192]
# Overview
Trust model of the `eigen-tangle-avs` is straightforward. The AVS runs a Tangle validator client. The operator is subject to all slashing conditions of the Tangle main chain, namely:
1. Consensus failures
2. Uptime / Offline absences

In addition to base layer validator misbehaviors, the operator/validator can register for Tangle Blueprints and provide Tangle Blueprint services to users. Each service may specify its own set of slashing conditions. If the Eigenlayer operator validator gets slashed on those, the messages will be relayed to Eigenlayer to slash assets on `eigen-tangle-avs`.

The operator will also be paid incentives both on the Tangle main chain as well as on Ethereum, to incentivize Eigenlayer operators to participate on our AVS.

## Interoperability trust modeling
In order to properly send information between Tangle and Ethereum, where `eigen-tangle-avs` is defined, we must leverage some cross-chain messaging protocol. The only currently integrated (or being integrated) protocol to accomplish this is [Sygma](https://buildwithsygma.com/). The Sygma system relies on a trusted set of MPC authorities who sign messages and relay them to their destinations.

We will need an upgrade-able smart contract on Ethereum that can handle the following:
- Specify  _**cross-chain message origins**_. We will start with 1 (Sygma) but grow to encompass more _oracles_ and zk proof based methods.
- Receiving messages and authenticating from a **cross-chain message origin**.
- The two categories of messages we consider are those for _slashing_ and those for _rewards_.
- Rewards should be dispatched at the end of an epoch on Tangle main chain.
- Slashes should be dispatched after they have been applied (it is possible to negate a slashing through governance).

**Comment by Tjemmmic** [comment]
Moved to https://github.com/webb-tools/eigensdk-rs
