### ISSUE TITLE
[CHECKLIST] MP-ECDSA Protocol

### ISSUE THREAD

**Issue by tbraun96** [webb-tools/gadget#26]
Code from the `dkg-gadget` crate of the `dkg-substrate` repo must be refactored inside the new gadget/protocol model provided by this repository to create a more robust, maintainable, and streamlined implementation.

Since the dkg has two types of protocols (keygen and signing), we can run two different protocols via `webb_gadget::run_protocol` selected twice, sharing some state that allows the signing to use the keygen's output public key. Thus, this task will include these two different phases.

**Phase I: Keygen Protocol**
- [x] #27
- [x] #28

**Phase II: Signing Protocol**
- [x] #29
- [x] #30

Ideally, there would be no need for an in-memory shared state between the `KeygenProtocol` and the `SigningProtocol`. Instead, we would use the off-chain storage as we currently do in the DKG to fetch keys for a specific session.

Since the function `webb_gadget::run_protocol` also requires a connection to a blockchain and a network implementation, we will also need to complete the following tasks:

**Phase III: Networking**
- [x] #31
- [x] #32
- [x] #39

Note: the client should be identical between the keygen and signing protocols. The network will be nearly identical, the only difference being that the underlying network stream will be multiplexed to split signing and keygen messages.

Next, the two protocols for keygen and signing will need to be put together as such:

```rust
let keygen_protocol_future = webb_gadget::run_protocol(keygen_gossip_network, keygen_protocol, blockchain_connection.clone());
let signing_protocol_future = webb_gadget::run_protocol(signing_gossip_network, signing_protocol, blockchain_connection);

tokio::select! {
    res0 = keygen_protocol_future => res0,
    res1 = signing_protocol_future => res1,
}
```

Thus, this step of tying together the two protocols and creating a program entrypoint with a main function will need to be encapsulated in an additional step:

**Phase IV: Application Binary**
- [ ] #33

Finally, everything must be tested:

**Phase V: Testing**
- [x] #34
- [ ] #35

**Comment by shekohex** [comment]
Reopening this checklist, as there are a few tasks that needs to be done first to complete the whole workflow.
