### ISSUE TITLE
[TASK] Context Derives - Defaults and additional options

### ISSUE THREAD

**Issue by Tjemmmic** [webb-tools/gadget#265]
# Overview

Introduce Derive macros for `GadgetConfiguration` (`Context`) to simplify the implementation of common traits and functionalities. These derives will automatically handle boilerplate code, such as the implementation of the keystore, Tangle client, and standard defaults, allowing developers to focus on core logic without manual implementation of repetitive tasks.

## Checklist

- [x] `KeystoreContext`: Automatically implement the keystore trait for any struct that derives WithKeystore. This will provide out-of-the-box support for secure key management.
- [x] `SubxtClientContext`: Automatically implement the client function that returns a new subxt::OnlineClient instance for interacting with the Tangle. This will streamline integration with the Tangle network.
- [ ] `StandardDefaults`: (__Name will change__) Automatically derive a set of common derives (e.g., Default, Clone, Debug, PartialEq) for GadgetConfiguration, reducing the need for manual derivations and ensuring consistency.
- [x] Specific keystore derives for functions specific to each key type e.g., `first_ecdsa_signer`
- [x] `ServiceContext`: Automatically gives you access to the current service instance, current operators set, ..etc
- [x] Tests for each Derive
- [x] #320
- [x] Document the derives - #271

**Comment by drewstone** [comment]
Pseudocode examples would be helpful, but generally I think my first feeling about naming is that I don't like these names or deriving `WithKeystore` feels off.

**Comment by shekohex** [comment]
This checklist is almost done, the remaining task is caching the clients.

**Comment by shekohex** [comment]
This checklist is now done!
