### ISSUE TITLE
[TASK] Docs - Context Derive Options

### ISSUE THREAD

**Issue by Tjemmmic** [webb-tools/gadget#271]
# Overview

__Note: This is a further defined task to outline the documentation of the Derive Macros for Context/GadgetConfiguration. The task for this feature can be found [here.](https://github.com/webb-tools/gadget/issues/265)__

Derives will easily implement common functionalities into GadgetConfiguration as a developer wants. More options will be added, but the checklist includes those that are currently planned. Documentation for these options is extremely important to allow developers to quickly determine what they want to include based on their needs.

## Checklist

- [x] `WithKeystore`
- [ ] `WithTangleClient`
- [x] `StandardDefaults`
- [x] Specific keystore derives for functions specific to each key type e.g., `first_ecdsa_signer`

**Comment by shekohex** [comment]
Done in https://github.com/webb-tools/tangle-docs/pull/62

Preview: https://deploy-preview-59--tangle-docs.netlify.app/developers/blueprint-macros/context
