### ISSUE TITLE
[TASK] Default context must contain information about the service instance.

### ISSUE THREAD

**Issue by drewstone** [webb-tools/gadget#290]
# Overview
If I'm a developer of a blueprint, it needs to be extremely clear and easy how to get the information about my service instance. On Tangle this is some entirely reusable and consistent thing, on Eigenlayer it's more specific to the AVS contracts, and other platforms probably also specific. Nonetheless, defining this for Eigenlayer and any customization we need on Tangle side needs to be extremely clear and easy to get (BlueprintManager contract might have custom data from a custom registration hook).

## Features
- Who are the operators? What is their metadata
- What is the stake distribution of the operators?
- What is the service instance metadata?
- What are my contract addresses? This is nice if I want to interact with them in the hooks/jobs/reports

**Comment by shekohex** [comment]
Done in #321
