### ISSUE TITLE
[TASK] Signer Selections

### ISSUE THREAD

**Issue by shekohex** [webb-tools/gadget#55]
### Goal

Given an $`n`$ amount of participants, choose $`t`$ participant _randomly_ to participate and run the signing protocol.

### Random* Selection

This algorithm is not cryptographically random, instead it will use a seed of different values while ensuring that these values are the same across different nodes. Let $`S`$ is the seed, where $`S = keccak256(jobId, retryId, now)`$ then, we can use that seed to pick random participants from the participants list.

**Comment by drewstone** [comment]
Is `now` going to be the same across parties? Also I thought we solved this a long time ago, why not just choose what we did before?

**Comment by shekohex** [comment]
> Is `now` going to be the same across parties? Also I thought we solved this a long time ago, why not just choose what we did before?

Yes, Now is the finality notification block number.
And No, It did not work as expected. Needs a bit of tweaking to get it to work with CGGMP21 Implementation.
